#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Dec  2 23:22:34 2019

@author: kylamae
"""

import pandas as pd

messy = {'Box': ['Box 1','Box 1','Box 1','Box 2','Box 2','Box 2'], 'Dimension': ['Length','Width','Height','Length','Width','Height'], 'Value': [6, 4, 2, 5, 3, 4]}

data = pd.DataFrame(messy,columns=['Box','Dimension','Value'])
tidy_data = data.pivot_table(index = ['Box'], columns = 'Dimension', values = 'Value').reset_index()

addvol = tidy_data.iloc[0,1]*tidy_data.iloc[0,2]*tidy_data.iloc[0,3]
addvol2 = tidy_data.iloc[1,1]*tidy_data.iloc[1,2]*tidy_data.iloc[1,3]
addcol = tidy_data['Volume'] = [addvol, addvol2]
